logger:
  level: INFO
  filename: "app.log"
  file_rotating_when: "midnight"
  file_rotating_backup_count: 7
  file_encoding: "utf-8"

port: 8000

mihome_config:
  auth_file: "auth.json"
  devices_file: "devices.json"
  interval_seconds: 5

qweather_config:
  api_key: "<api_key>"
  api_host: "<api_host>"
  interval_seconds: 5
  locations:
    - name: "家"
      lon: 121.63
      lat: 31.19
