logger:
  level: INFO
  filename: "app.log"
  file_rotating_when: "midnight"
  file_rotating_backup_count: 7
  file_encoding: "utf-8"

port: 8000
auth_file: "auth.json"
devices_file: "devices.json"
interval_seconds: 5

devices:
  - name: "电脑桌插座"
  - name: "热水器插座"
  - name: "台灯插座"
  - name: "温湿度计"
  - name: "路由器"
